name: Multi Container App Deployment
on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build tests docker image
        run: docker build -t mihalichzh/client-test -f ./Dockerfile.dev .
        working-directory: ./client
      
      - name: Run image with tests
        run: docker run mihalichzh/client-test npm test -- --watchAll=false

      - name: Build production versions of all images
        run: |
          docker build -t mihalichzh/multi-client ./client
          docker build -t mihalichzh/multi-nginx ./nginx
          docker build -t mihalichzh/multi-server ./server
          docker build -t mihalichzh/multi-worker ./worker
        working-directory: .
      - name: Publish images to the Docker Hub
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push mihalichzh/multi-client
          docker push mihalichzh/multi-nginx
          docker push mihalichzh/multi-server
          docker push mihalichzh/multi-worker
