name: Multi Container App Deployment
on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build tests docker image
        run: docker build -t mihalichzh/react-test -f ./Dockerfile.dev .
        working-directory: ./client
